global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'consul'
    metrics_path: /v1/agent/metrics
    params:
      format: ['prometheus']
    static_configs:
      - targets:
        - consul.service.dc1.pn.local:8500

  - job_name: 'consul-exporter'
    static_configs:
      - targets:
        - consul-exporter:9107
