@startuml
skinparam backgroundColor transparent

rectangle "VPN" as vpn {
    !include balancer.puml
    !include front.puml
    !include back.puml
    !include db.puml
    !include store.puml
}

bl <--> f : 172.x/16
bl <--> b : 172.x/16
bl <--> db : 172.x/16
bl <--> s : 172.x/16
@enduml
